---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path = ../' >> ansible.cfg
  - printf '\host_key_checking = False' >> ansible.cfg

script:
  # Basic role syntax check
  - env
  - ifconfig -a
  - cd ../
  - ln -s $(pwd)/ansible-role-kvm_host $(pwd)/kvm_host
  - cd -
  - find ../
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/