---
services: docker

# Use the new container infrastructure
sudo: required

env:
  - distro: ubuntu1604
    init: /lib/systemd/systemd
    #run_opts: "--privileged"
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    playbook: test.yml
  # - distro: centos7
  #   init: /usr/lib/systemd/systemd
  #   run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  #   playbook: centos-7-test.yml

services:
  - docker

before_install:
  - 'docker pull ubuntu:xenial'
  # - 'docker pull williamyeh/ansible:ubuntu16.04'

script:

  - container_id=$(mktemp)

  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} ubuntu:xenial "${init}" > "${container_id}"'

  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm whoami'

  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm sudo apt-get update && sudo apt-get -y install ansible python2.7'

  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --syntax-check'

  - 'docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --connection=local --sudo'

  - idempotence=$(mktemp)
  - docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --connection=local --sudo | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/