---
# tasks file for kvm_host

- include: '{{ ansible_distribution | lower }}.yml'


- name: Check if module(kvm) is present
  shell: '(lsmod | grep -q kvm) 2>/dev/null || echo 0'
  register: module_is_exist

# - debug:
#     var: module_is_exist

- name: Enable kernel modules - kvm
  modprobe:
    name: 'kvm'
    state: present
  when: ansible_virtualization_type != 'docker' and module_is_exist.stdout == 1



- name: Check if module(kvm_intel) is present
  shell: '(lsmod | grep -q kvm_intel) 2>/dev/null || echo 0'
  register: module_is_exist

# - debug:
#     var: module_is_exist

- name: Enable kernel modules - kvm_intel
  modprobe:
    name: 'kvm_intel'
    state: present
  when: ansible_virtualization_type != 'docker' and module_is_exist.stdout == 1
