---
# tasks file for kvm_host

- include: '{{ ansible_distribution | lower }}.yml'


- name: Enable kernel modules - kvm
  modprobe:
    name: 'kvm'
    state: present
  when: ansible_virtualization_type != 'docker'


- name: Enable kernel modules - kvm_intel
  modprobe:
    name: 'kvm_intel'
    state: present
  when: ansible_virtualization_type != 'docker'
