---
# tasks file for kvm_host

- name: Install KVM-related packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    update_cache: 'yes'
  with_items:
    - 'libvirt-bin'
    - 'netcat-openbsd'
    - 'gawk'
    - 'qemu-system'
    - 'pm-utils'
    - 'ebtables'
    - 'qemu-kvm'
    - 'virtinst'
    - 'bridge-utils'
    - 'cpu-checker'
    - 'openvswitch-switch'
    - 'vlan'
    - 'ifenslave'
    - 'python-lxml'


- name: Enable Necessary Modules (1/2)
  lineinfile:
    dest: /etc/modules
    line: '{{ item }}'
  with_items:
    - '8021q'
    - 'bonding'
  when: ansible_os_family == 'Debian'


- name: Enable Necessary Modules (2/2)
  modprobe:
    name: '{{ item }}'
    state: present
  with_items:
    - '8021q'
    - 'bonding'
  when: ansible_os_family == 'Debian'


- name: Enable IPv4 Forward
  lineinfile:
    dest: /etc/sysctl.conf
    line: 'net.ipv4.ip_forward = 1'
  when: ansible_os_family == 'Debian'