---
# tasks file for kvm_host

- include_tasks: '{{ ansible_distribution | lower }}.yml'
  when: ansible_virtualization_type != 'docker'


- name: automatically load kvm & kvm_intel kernel modules (1/2)
  file:
    path: "/etc/modules-load.d/{{ item }}.conf"
    mode: 0644
    state: touch
  with_items:
    - "kvm"
    - "kvm_intel"
  when: ansible_virtualization_type != 'docker'
  
- name: automatically load kvm & kvm_intel kernel modules (2/2)
  lineinfile:
    dest: "/etc/modules-load.d/{{ item}}.conf"
    line: '{{ item }}'
  with_items:
    - "kvm"
    - "kvm_intel"
  when: ansible_virtualization_type != 'docker'


- name: enable kvm nested virtualization
  lineinfile:
    dest: "/etc/modprobe.d/qemu-system-x86.conf"
    line: 'options kvm_intel nested=1'
  when: ansible_distribution == "Debian" and ansible_virtualization_type != 'docker'

- name: enable kvm nested virtualization
  lineinfile:
    dest: "/etc/modprobe.d/kvm.conf"
    line: 'options kvm_intel nested=1'
  when: ansible_distribution == "RedHat" and ansible_virtualization_type != 'docker'


- name: reload kernel module
  service: name=systemd-modules-load.service state=restarted
  when: ansible_virtualization_type != 'docker'

- name: check installation status
  command: virt-host-validate
  ignore_errors: yes
  register: cmd_output
  when: ansible_virtualization_type != 'docker'

- debug:
    var: cmd_output.stdout_lines
  when: ansible_virtualization_type != 'docker'
