---
# tasks file for kvm_host

- include: '{{ ansible_distribution | lower }}_{{ ansible_distribution_version }}.yml'


- name: Start Network interfaces
  shell: "ifup {{ item }}"
  with_items: '{{ kvm_host_LinuxBondNics }}'
  when: kvm_host_ConfigBondInterface


- name: Create a bridge named {{ kvm_host_OvsBridgeName }}
  openvswitch_bridge:
    bridge: '{{ kvm_host_OvsBridgeName }}'
    state: present
  when: kvm_host_ConfigOvsBridge

- name: Creates port {{ kvm_host_LinuxBondName }} on bridge {{ kvm_host_OvsBridgeName }}
  openvswitch_port:
    bridge: '{{ kvm_host_OvsBridgeName }}'
    port: '{{ kvm_host_OVsBridgePortInterface }}'
    state: present
  when: kvm_host_ConfigOvsBridge

- name: Define Virtual Network for OVS Bridge (1/3)
  virt_net:
    command: define
    name: '{{ kvm_host_OvsBridgeName }}'
    xml: '{{ lookup("template", "templates/virsh_net.xml.j2") }}'
  when: kvm_host_ConfigOvsBridge

- name: Define Virtual Network for OVS Bridge (2/3)
  virt_net:
    state: active
    name: '{{ kvm_host_OvsBridgeName }}'
  when: kvm_host_ConfigOvsBridge

- name: Define Virtual Network for OVS Bridge (3/3)
  virt_net:
    autostart: yes
    name: '{{ kvm_host_OvsBridgeName }}'
  when: kvm_host_ConfigOvsBridge