- name: Install KVM-related 
s
  apt:
    name: '{{ item }}'
    state: 'latest'
    update_cache: 'yes'
  with_items:
    - 'libvirt-bin'
    - 'netcat-openbsd'
    - 'gawk'
    - 'qemu-system'
    - 'pm-utils'
    - 'ebtables'
    - 'qemu-kvm'
    - 'virtinst'
    - 'bridge-utils'
    - 'cpu-checker'
    - 'python-lxml'
    - 'libguestfs-tools'
  notify: restart libvirtd
  when: ansible_virtualization_type != 'docker'

# only for ubuntu 14.04
#- name: update ipex_qemu (1/3) => download 

#  get_url:
#    url: http://security.ubuntu.com/ubuntu/pool/main/i/ipxe/ipxe-qemu_1.0.0+git-20150424.a25a16d-1ubuntu2_all.deb
#    dest: /tmp/ipxe-qemu_1.0.0+git-20150424.a25a16d-1ubuntu2_all.deb
#  when: ansible_virtualization_type != 'docker' and ansible_distribution_release == 'trusty'

- name: modify libvirt directory permissions (1/2)
  acl:
    path: /var/lib/libvirt/images
    entity: libvirt-qemu
    etype: user
    permissions: rwx
    recursive: yes
    default: yes
    state: present
  when: ansible_virtualization_type != 'docker'
  
- name: modify libvirt directory permissions (2/2)
  acl:
    path: /var/lib/libvirt/images
    entity: kvm
    etype: group
    permissions: rx
    recursive: yes
    default: yes
    state: present
  when: ansible_virtualization_type != 'docker'

  # file:
  #   path: '/var/lib/libvirt/images'
  #   state: directory
  #   recurse: 'yes'
  #   owner: libvirt-qemu
  #   group: kvm
  #   mode: 0755
  # when: ansible_virtualization_type != 'docker'

# only for ubuntu 14.04
- name: update ipex_qemu (2/3) => install 

  apt:
    deb: http://security.ubuntu.com/ubuntu/pool/main/i/ipxe/ipxe-qemu_1.0.0+git-20150424.a25a16d-1ubuntu2_all.deb
  when: ansible_virtualization_type != 'docker' and ansible_distribution_release == 'trusty'

# only for ubuntu 14.04
- name: update ipex_qemu (3/3) => remove 

  file:
    path: /tmp/ipxe-qemu_1.0.0+git-20150424.a25a16d-1ubuntu2_all.deb
    state: absent
  when: ansible_virtualization_type != 'docker' and ansible_distribution_release == 'trusty'

# only for ubuntu 14.04
- name: fix "/usr/bin/supermin-helper error" when using libguestfs-tools
  command: "update-guestfs-appliance"
  when: ansible_virtualization_type != 'docker' and ansible_distribution_release == 'trusty'