- name: Install KVM-related packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    update_cache: 'yes'
  with_items:
    - 'libvirt-bin'
    - 'netcat-openbsd'
    - 'gawk'
    - 'qemu-system'
    - 'pm-utils'
    - 'ebtables'
    - 'qemu-kvm'
    - 'virtinst'
    - 'bridge-utils'
    - 'cpu-checker'
    - 'python-lxml'
    - 'libguestfs-tools'
  notify: restart libvirtd
  when: ansible_virtualization_type != 'docker'

- name: fix "/usr/bin/supermin-helper error" when using libguestfs-tools
  command: "update-guestfs-appliance"
  when: ansible_virtualization_type != 'docker'