- name: Install KVM-related packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    update_cache: 'yes'
  with_items:
    - 'libvirt-bin'
    - 'netcat-openbsd'
    - 'gawk'
    - 'qemu-system'
    - 'pm-utils'
    - 'ebtables'
    - 'qemu-kvm'
    - 'virtinst'
    - 'bridge-utils'
    - 'cpu-checker'
    - 'python-lxml'
    - 'libguestfs-tools'
  notify: "restart libvirtd in {{ ansible_os_family }} family"


- name: modify libvirt directory permissions (1/2)
  acl:
    path: /var/lib/libvirt/images
    entity: libvirt-qemu
    etype: user
    permissions: rwx
    recursive: yes
    default: yes
    state: present
  
- name: modify libvirt directory permissions (2/2)
  acl:
    path: /var/lib/libvirt/images
    entity: kvm
    etype: group
    permissions: rx
    recursive: yes
    default: yes
    state: present

# only for ubuntu 14.04
- name: update ipex_qemu => install 

  apt:
    deb: http://security.ubuntu.com/ubuntu/pool/main/i/ipxe/ipxe-qemu_1.0.0+git-20150424.a25a16d-1ubuntu2_all.deb
  when: ansible_distribution_release == 'trusty'


# only for ubuntu 14.04
- name: fix "/usr/bin/supermin-helper error" when using libguestfs-tools
  command: "update-guestfs-appliance"
  when: ansible_distribution_release == 'trusty'

- name: enable intel_iommu
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="intel_iommu=on"'
    
- name: generate new grub.cfg
  command: "grub-mkconfig -o /boot/grub/grub.cfg"
