---
# tasks file for kvm_host with Ubuntu 16.04

- name: Install KVM-related packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    update_cache: 'yes'
  with_items:
    - 'libvirt-bin'
    - 'netcat-openbsd'
    - 'gawk'
    - 'qemu-system'
    - 'pm-utils'
    - 'ebtables'
    - 'qemu-kvm'
    - 'virtinst'
    - 'bridge-utils'
    - 'cpu-checker'
    - 'openvswitch-switch'
    - 'vlan'
    - 'ifenslave'
    - 'python-lxml'


- name: Config kernel modules - Bonding
  lineinfile:
    dest: /etc/modules
    line: 'bonding'
  when: kvm_host_ConfigBondInterface


- name: Enable kernel modules - Bonding
  modprobe:
    name: 'bonding'
    state: present
  when: kvm_host_ConfigBondInterface


- name: Config kernel modules - VLAN
  lineinfile:
    dest: /etc/modules
    line: '8021q'
  when: kvm_host_ConfigOvsBridge


- name: Enable kernel modules - VLAN
  modprobe:
    name: '8021q'
    state: present
  when: kvm_host_ConfigOvsBridge


- name: Enable IPv4 ip_forward
  lineinfile:
    dest: /etc/sysctl.conf
    line: 'net.ipv4.ip_forward = 1'
  when: kvm_host_ConfigOvsBridge


- name: Configure Linux bonding master interface (mode 6)
  template:
    src: templates/ubuntu_bond.cfg.j2
    dest: /etc/network/interfaces.d/{{ kvm_host_LinuxBondName }}.cfg
  notify: restart networking.service
  when: kvm_host_ConfigBondInterface

- name: Configure Linux bonding slave interfaces
  template:
    src: templates/ubuntu_bond_nic.cfg.j2
    dest: /etc/network/interfaces.d/ovs_bond_{{ item }}.cfg
  with_items: '{{ kvm_host_LinuxBondNics }}'
  notify: restart networking.service
  when: kvm_host_ConfigBondInterface


- name: Configure VLAN interfaces on trunking ports
  template:
    src: templates/ubuntu_bond_nic.cfg.j2
    dest: /etc/network/interfaces.d/ubuntu_bond_vlan{{ item.vlan_id }}.cfg.j2
  with_items: '{{ kvm_host_MultiVlans }}'
  notify: restart networking.service
  when: kvm_host_ConfigMultiVlans